/* A polyfill for browsers that don't support ligatures. */
/* The script tag referring to this file must be placed before the ending body tag. */

/* To provide support for elements dynamically added, this script adds
   method 'icomoonLiga' to the window object. You can pass element references to this method.
*/
(function () {
    'use strict';
    function supportsProperty(p) {
        var prefixes = ['Webkit', 'Moz', 'O', 'ms'],
            i,
            div = document.createElement('div'),
            ret = p in div.style;
        if (!ret) {
            p = p.charAt(0).toUpperCase() + p.substr(1);
            for (i = 0; i < prefixes.length; i += 1) {
                ret = prefixes[i] + p in div.style;
                if (ret) {
                    break;
                }
            }
        }
        return ret;
    }
    var icons;
    if (!supportsProperty('fontFeatureSettings')) {
        icons = {
            'upload-bold': '&#xe97f;',
            'cancel-circle': '&#xe97c;',
            'cancel-appointment': '&#xe97c;',
            'check-circle': '&#xe97d;',
            'confirm-appointment': '&#xe97d;',
            'resend-circle': '&#xe97e;',
            'reschedule-circle': '&#xe97e;',
            'reschedule-appointment': '&#xe97e;',
            'add-bold': '&#xe97b;',
            'plus-bold': '&#xe97b;',
            'text': '&#xe978;',
            'file-text': '&#xe978;',
            'file-doc': '&#xe978;',
            'file-word': '&#xe978;',
            'gender': '&#xe979;',
            'resend': '&#xe97a;',
            'redo': '&#xe97a;',
            'billing': '&#xe973;',
            'coins': '&#xe973;',
            'invoice': '&#xe974;',
            'payment': '&#xe975;',
            'coin': '&#xe975;',
            'void-invoice': '&#xe976;',
            'invoice-void': '&#xe976;',
            'void': '&#xe977;',
            'erase': '&#xe972;',
            'eraser': '&#xe972;',
            'filter': '&#xe970;',
            'undo': '&#xe971;',
            'send': '&#xe96f;',
            'send-chat': '&#xe96f;',
            'save': '&#xe96e;',
            'floppy-disk': '&#xe96e;',
            'assistant': '&#xe96d;',
            'file-audio': '&#xe967;',
            'audio': '&#xe967;',
            'file-excel': '&#xe968;',
            'excel': '&#xe968;',
            'file-presentation': '&#xe969;',
            'ppt': '&#xe969;',
            'presentation': '&#xe969;',
            'file-video': '&#xe96a;',
            'video-camera': '&#xe96a;',
            'video': '&#xe96a;',
            'folder': '&#xe96b;',
            'support': '&#xe96c;',
            'intercom': '&#xe96c;',
            'caret': '&#xe964;',
            'nonvisible': '&#xe965;',
            'visible': '&#xe966;',
            'eye': '&#xe966;',
            'appointment-canceled': '&#xe95f;',
            'canceled': '&#xe95f;',
            'appointment-confirmed': '&#xe960;',
            'confirmed': '&#xe960;',
            'appointment-missed': '&#xe961;',
            'appointment-noshow': '&#xe961;',
            'missed': '&#xe961;',
            'noshow': '&#xe961;',
            'appointment-new': '&#xe962;',
            'rescheduled': '&#xe963;',
            'reschedule': '&#xe963;',
            'appointment-reschedule': '&#xe963;',
            'appointment-rescheduled': '&#xe963;',
            'download': '&#xe959;',
            'huli': '&#xe95a;',
            'h': '&#xe95a;',
            'job': '&#xe95b;',
            'work': '&#xe95b;',
            'suitcase': '&#xe95b;',
            'occupation': '&#xe95b;',
            'play': '&#xe95c;',
            'play-video': '&#xe95c;',
            'treatment': '&#xe95d;',
            'stethoscope': '&#xe95d;',
            'upload': '&#xe95e;',
            'flash': '&#xe952;',
            'flip': '&#xe953;',
            'flip-camera': '&#xe953;',
            'rotate-left': '&#xe954;',
            'rotate-l': '&#xe954;',
            'rotate-r': '&#xe955;',
            'rotate-right': '&#xe955;',
            'pdf': '&#xe956;',
            'file-pdf': '&#xe956;',
            'file-other': '&#xe957;',
            'file-any': '&#xe957;',
            'positive': '&#xe958;',
            'new': '&#xe958;',
            'add-circle': '&#xe958;',
            'summary': '&#xe951;',
            'patient-summary': '&#xe951;',
            'ehr-summary': '&#xe951;',
            'menu': '&#xe950;',
            'hamburger': '&#xe950;',
            'add': '&#xe900;',
            'plus': '&#xe900;',
            'age-adult': '&#xe901;',
            'adult': '&#xe901;',
            'age-elder': '&#xe902;',
            'elder': '&#xe902;',
            'age-kid': '&#xe903;',
            'kid': '&#xe903;',
            'age-baby': '&#xe904;',
            'baby': '&#xe904;',
            'toddler': '&#xe904;',
            'arrow-down': '&#xe905;',
            'down': '&#xe905;',
            'arrow-left': '&#xe906;',
            'back': '&#xe906;',
            'left': '&#xe906;',
            'arrow-right': '&#xe907;',
            'right': '&#xe907;',
            'arrow-up': '&#xe908;',
            'up': '&#xe908;',
            'badge': '&#xe909;',
            'view-bagde': '&#xe909;',
            'grid': '&#xe909;',
            'view-grid': '&#xe909;',
            'patient': '&#xe90a;',
            'basic-info': '&#xe90a;',
            'patient-file': '&#xe90a;',
            'ficha': '&#xe90a;',
            'ficha-basica': '&#xe90a;',
            'person': '&#xe90a;',
            'birthday': '&#xe90b;',
            'cake': '&#xe90b;',
            'online-appointment': '&#xe90c;',
            'huli-calendar': '&#xe90c;',
            'calendar': '&#xe90d;',
            'agenda': '&#xe90d;',
            'camera': '&#xe90e;',
            'photo': '&#xe90e;',
            'view-card': '&#xe90f;',
            'card': '&#xe90f;',
            'caution': '&#xe910;',
            'warning': '&#xe910;',
            'chat': '&#xe911;',
            'check': '&#xe912;',
            'done': '&#xe912;',
            'accept': '&#xe912;',
            'checkup': '&#xe913;',
            'clinic': '&#xe914;',
            'hospital': '&#xe914;',
            'clock': '&#xe915;',
            'time': '&#xe915;',
            'close': '&#xe916;',
            'exit': '&#xe916;',
            'quit': '&#xe916;',
            'code': '&#xe917;',
            'copy': '&#xe918;',
            'credit-card': '&#xe919;',
            'delete': '&#xe91a;',
            'trash': '&#xe91a;',
            'angle-down': '&#xe91b;',
            'downgrade': '&#xe91c;',
            'rocket-down': '&#xe91c;',
            'drop': '&#xe91d;',
            'blood': '&#xe91d;',
            'edit': '&#xe91e;',
            'pencil': '&#xe91e;',
            'export': '&#xe91f;',
            'feedback': '&#xe920;',
            'flag': '&#xe921;',
            'gender-boy': '&#xe922;',
            'boy': '&#xe922;',
            'man': '&#xe922;',
            'gender-female': '&#xe923;',
            'female': '&#xe923;',
            'gender-girl': '&#xe924;',
            'girl': '&#xe924;',
            'woman': '&#xe924;',
            'gender-male': '&#xe925;',
            'male': '&#xe925;',
            'heart-solid': '&#xe926;',
            'heart-fill': '&#xe926;',
            'heart': '&#xe927;',
            'help': '&#xe928;',
            'lifesaver': '&#xe928;',
            'id': '&#xe929;',
            'image': '&#xe92a;',
            'file-image': '&#xe92a;',
            'info': '&#xe92b;',
            'laboratory': '&#xe92c;',
            'documents': '&#xe92c;',
            'language': '&#xe92d;',
            'angle-left': '&#xe92e;',
            'lock': '&#xe92f;',
            'logout': '&#xe930;',
            'medical-history': '&#xe931;',
            'history': '&#xe931;',
            'medical-record': '&#xe931;',
            'merge': '&#xe932;',
            'message': '&#xe933;',
            'mail': '&#xe933;',
            'email': '&#xe933;',
            'negative': '&#xe934;',
            'minus-circle': '&#xe934;',
            'hyphen-circle': '&#xe934;',
            'missed-appointment': '&#xe934;',
            'no': '&#xe935;',
            'block': '&#xe935;',
            'note': '&#xe936;',
            'notification': '&#xe937;',
            'bell': '&#xe937;',
            'options': '&#xe938;',
            'more': '&#xe938;',
            'phone-home': '&#xe939;',
            'phone-mobile': '&#xe93a;',
            'mobile': '&#xe93a;',
            'phone-office': '&#xe93b;',
            'fax': '&#xe93b;',
            'phone': '&#xe93c;',
            'place': '&#xe93d;',
            'gps': '&#xe93d;',
            'location': '&#xe93d;',
            'print': '&#xe93e;',
            'printer': '&#xe93e;',
            'profile': '&#xe93f;',
            'doctor': '&#xe93f;',
            'records': '&#xe940;',
            'ehr': '&#xe940;',
            'patients': '&#xe940;',
            'refresh-no': '&#xe941;',
            'refresh': '&#xe942;',
            'angle-right': '&#xe943;',
            'search': '&#xe944;',
            'loupe': '&#xe944;',
            'settings': '&#xe945;',
            'preferences': '&#xe945;',
            'share': '&#xe946;',
            'sort': '&#xe947;',
            'star-solid-half': '&#xe948;',
            'star-half': '&#xe948;',
            'star-solid': '&#xe949;',
            'star-filled': '&#xe949;',
            'star-black': '&#xe949;',
            'review': '&#xe949;',
            'star': '&#xe94a;',
            'star-line': '&#xe94a;',
            'view-table': '&#xe94b;',
            'table': '&#xe94b;',
            'tag': '&#xe94c;',
            'unlock': '&#xe94d;',
            'angle-up': '&#xe94e;',
            'upgrade': '&#xe94f;',
          '0': 0
        };
        delete icons['0'];
        window.icomoonLiga = function (els) {
            var classes,
                el,
                i,
                innerHTML,
                key;
            els = els || document.getElementsByTagName('*');
            if (!els.length) {
                els = [els];
            }
            for (i = 0; ; i += 1) {
                el = els[i];
                if (!el) {
                    break;
                }
                classes = el.className;
                if (/lnr/.test(classes)) {
                    innerHTML = el.innerHTML;
                    if (innerHTML && innerHTML.length > 1) {
                        for (key in icons) {
                            if (icons.hasOwnProperty(key)) {
                                innerHTML = innerHTML.replace(new RegExp(key, 'g'), icons[key]);
                            }
                        }
                        el.innerHTML = innerHTML;
                    }
                }
            }
        };
        window.icomoonLiga();
    }
}());
